# Generated by Django 5.0.2 on 2024-03-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):


    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
    ]
